Fixed error message w.r.t. fillbyte value.
Made OOLAG not swallow illegal argument exceptions.

Changed SDE to be very defensive when doing a toString of a cause
exception. It aborts if anything throws from there.

Created EDIFACT in daffodil-examples

Fixed unnecessary requirement for generateEscapeBlock property

When the escape scheme is an escape-character kind, this property should
not be required.

Changes to support EDIFACT. (Doesn't yet work though)

Temporarilly changed runtime SDE if a variable has been read before
being set into a runtime SDW to work around DFDL-1443.

Added ignoreCase to TermRuntimeData so it will be available when needed
in the runtime. However, nothing looks at it still.

Changed DFA compiler method from 'compile' to compileDelimiter. Too many
things named 'compile'.  Hard to search in the code.

Status: EDIFACT schema compiles, but we get a parse error now:

edu.illinois.ncsa.daffodil.tdml.TDMLException: Parse Error:
Term('CompiledExpression({$ibmEdiFmt:SegmentTerm})') - element.UNB:
Delimiter not found!  Was looking for (<DFA lookingFor=''%WSP*;' />,
<DFA lookingFor='%NL;%WSP*;' />) but found "++1'␊UNH+3" instead.
Schema context: element.UNB Location line 58 column 10 in
file:/home/mbeckerle/Documents/dataiti/git/daffodil/eclipse-projects/examples/target/eclipse/classes/EDIFACT-SupplyChain-D03B/EDIFACT-SupplyChain-Messages-D.03B.xsd
Data location was preceding byte 89 limit(bytes) 806

Changes to allow HL7 example.

Changed dfdl:defineFormat to allow comments to sit before/after the
child dfdl:format element.

The schema compiles (needs -Xmx8G), but it does not yet run
successfully:

Parse Error: Sep('CompiledExpression(|)') - sequence: Found delimiter
(%NL;) for element.HL7::LocalComplexTypeDef::sequence::element.MSH when
looking for Sep(<DFA lookingFor='|' /> <DFA lookingFor='%NL;' />) for
element.HL7::LocalComplexTypeDef::sequence::element.MSH::GlobalComplexTypeDef(MSH.CONTENT)::sequence::sequence
after element.MSH.17.CountryCode and before sequence[1]
Schema context: sequence Location line 1984 column 20 in
file:/home/mbeckerle/Documents/dataiti/git/daffodil/eclipse-projects/examples/target/eclipse/classes/segments.xsd
Data location was preceding byte 82 limit(bytes) 433

Moved DFDLSchemas examples to daffodil-extra.

Bug in setVariable - needs UState for unparsing.

Add binaryNumberRep 'ibm4690Packed' enum to schemas of DFDL schema.

This is used in some of the DFDLSchemas on github, so causes compilation
to fail immediately.

Fixed bug when defaultValue="false" instead of "fn:false()" abort.

Happened in DFDLSchemas ISO8589

Change def to lazy val (efficiency).

Remove duplicate property names from this predefined format.

Note that there were two definitions of outputNewLine. One was CRLF, the
other LF. I have left it as LF.

Added readme to daffodil-examples re: PCAP schema's real home.

...which is on github DFDLSchemas PCAP site.

DFDL-1441, DFDL-999